version: "3.8"
services:
  db:
    container_name: casbin_playground_local_mysql
    image: mysql:latest
    ports: ["3306:3306"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - backend

  phpmyadmin:
    container_name: casbin_playground_local_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports: ["8090:80"]
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend

networks:
  backend:
    driver: bridge
